### ISSUE TITLE
hook.params.query.$disableSoftDelete is a security issue

### ISSUE THREAD

**Issue by Casedy** [feathers-plus/feathers-hooks-common#128]
### Steps to reproduce
I just try to softDelete some record. 
```
before = {
  remove: [
    commonHooks.softDelete()
  ]
}
```
### Expected behavior
soft delete happend

### Actual behavior
got error
```
info: GeneralError: unknown top level operator: $disableSoftDelete
    at GeneralError.ExtendableBuiltin (...~/node_modules/feathers-errors/lib/index.js:21:28)
    at GeneralError.FeathersError (...~/node_modules/feathers-errors/lib/index.js:96:116)
    at new GeneralError (...~/node_modules/feathers-errors/lib/index.js:281:109)
    at errorHandler (...~/node_modules/feathers-mongoose/lib/error-handler.js:32:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### System configuration
**Module versions** :
2.0.3
**Mongoose version**:
^4.8.5
**feathers-mongoose version**:
^4.0.1
**NodeJS version**:
v7.2.0
**Operating System**:
macosx
**Module Loader**:
webpack
**Mongodb version**:
3.4.2

**Comment by Casedy** [comment]
if I commented line 
```
          hook.params.query.$disableSoftDelete = true;
```
in 
```
      case 'remove':
        return Promise.resolve().then(function () {
          return hook.id ? throwIfItemDeleted(hook.id) : null;
        }).then(function () {
          hook.data[deleteField] = true;
          hook.params.query[deleteField] = { $ne: true };
          hook.params.query.$disableSoftDelete = true;

          return service.patch(hook.id, hook.data, hook.params).then(function (result) {
            hook.result = result;
            return hook;
          });
        });
```
it works fine.

**Comment by eddyystop** [comment]
softDelete is only intended to be an all hook. Please see if the problem
occurs in that case.

**Comment by ekryski** [comment]
@eddyystop I was actually noticing this issue as well. Any reason why we have that `$disableSoftDelete`? This is potentially a security issue because a client could pass that and delete records when it's not supposed to. In general, I think we want to stay away from special query params like this (which is a bigger discussion not for this issue).

**Comment by Casedy** [comment]
@eddyystop Maybe allow the flag only for internal requests?
But anyway, how I see, there is not such field ($disableSoftDelete) in `mongoose`/`mongodb`.

**Comment by eddyystop** [comment]
I think that should be `hook.params.$disableSoftDelete = true;`.

**Comment by Casedy** [comment]
@eddyystop 
> softDelete is only intended to be an all hook. Please see if the problem
occurs in that case.

Yep, this was the reason of me issue. 
I got it when found new documentation on the hook 
[https://auk.docs.feathersjs.com/api/hooks-common.html#softdelete](url)

**Comment by ekryski** [comment]
re-opening for visibility around this being a security issue.

**Comment by eddyystop** [comment]
| Casedy commented on Feb 28 • edited
| Maybe allow the flag only for internal requests?

I'll be doing that when I hit up the hooks again.

**Comment by roschaefer** [comment]
I pledge for the server *should* know. E.g. in our case, we want to generate unique attributes e.g. a `slug`. This slug shall be unique covering all records including soft-deleted records. In order to generate a unique slug the server must know if a soft deleted record with the same slug exists.

BTW: I'm facing `UnhandledPromiseRejectionWarning: MongoError: unknown top level operator: $disableSoftDelete` as @Casedy already pointed out.

**Comment by eddyystop** [comment]
`softDelete2` will be published once its docs are done, so I'll be closing this issue.

`softDelete2` is a notable improvement over `softDelete`. It has the equivalent `context.params.$ignoreDeletedAt` capability so calls can not ignore logically deleted records, but that can be disabled with softDelete2's `allowIgnoreDeletedAt` option.
