### ISSUE TITLE
populate a field in an array

### ISSUE THREAD

**Issue by lfabreges** [feathers-plus/feathers-hooks-common#142]
### Steps to reproduce
I'm trying to populate a field inside an array, I have the following model:
```
content: {
    members: [
        user: <this is the field to populate>,
        lastVisitAt: ...
    ]
}
```

I tried with the following include:
```js
include: [{
    asArray: true,
    childField: "_id",
    nameAs: "users",
    parentField: "members.user",
    service: "users",
}],
```

But `members.user` is undefined, because it's an array and `getByDot` don't know how to fetch all the values using this notation. I don't know if there is actually an other way to do it properly. It feels like `populate` should allow me to use nested include without trying to populate the `members` field if no relation is defined, something like:
```js
include: [{
    parentField: "members",
    include: [
        childField: "_id",
        nameAs: "user",
        parentField: "user",
        service: "users",
    ]
}],
```

**Comment by lfabreges** [comment]
I've managed to make it work with the following:
```js
{
    asArray: true,
    childField: "_id",
    nameAs: "users",
    parentField: "members",
    select: (_, parent) => parent.members ? ({ _id: { $in: parent.members.map(member => member.user) } }) : {},
    service: "users",
}
```

But I still think it should be handled differently. Feel free to close this issue if you feel like this workaround is acceptable.

Thanks.

**Comment by eddyystop** [comment]
There are syntax errors in your example
```js
content: {
    members: [
        user: <this is the field to populate>, // ???
        lastVisitAt: ...                       // ???
    ]
}
...
parentField: "members.user",                   // ???
```

Let me assume you meant `members: [user, lastVisitAt]`.

My first thought is that an array whose elements have different meanings is not a JavaScript way of doing things. `{ user: ..., lastVisitedAt: ... }` is what would be typical.

My second thought is that I think `members.0` would work.

The `select` option was added as a way of getting out of akward situations and, if `members.0` does not work, I think its appropriate here.

**Comment by lfabreges** [comment]
Sorry, I wrote it too fast.

members is an array containing objects. Each object contains a user field, the one that I want to populate, and others fields. 

For example:

members: [
  {
    user: "some id",
    field: "value"
  },
  {
    user: "other id",
    field: "bla"
  }
]

I want to populate the user field of each member. 

Example is not formatted, sorry, didn't found the backtick on my phone.

**Comment by eddyystop** [comment]
Processing an array is problematic exactly because people don't just want to process every element of that array, you want to use dot notation on every element of the array. And people have even asked to process other arrays nested at some level within the top array.

I suggest you place a hook function before populate which copies all the `hook.results.[].members.[].user` into an array and use that new array as the `parentField`. Something like

```js
hook => {
  (hook.result.data || hook.result).forEach(item => {
    item.users = members.map(member => member.user || null;
  });
  return hook;
};

// in populate
nameAs: "users",
parentField: "users",
```

**Comment by lfabreges** [comment]
I was thinking `include` could be processed without trying to populate the top level field if `service`, `childField`, ... were undefined.

Anyway, thank you, i'll stick with the `select`, it works.

**Comment by eddyystop** [comment]
I'm reopening this issue as this case (an array of objects where the objects contain the key) keeps popping up.

**Comment by eddyystop** [comment]
I've concluded there will be no end of special cases for where the keys are stored. Each special case will require special notation.  The docs will be harder to understand, the code more complex, the tests more expensive. There will be too much "magic".

I think the best way to handle this is using `select` as you did above. No magic, handles all cases.

I'm leaving this issue open as it has useful info for people.

**Comment by eddyystop** [comment]
The `fastJoin` hook added in Buzzard handles this case directly as well as other cases `populate` could not.

https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#fastJoin

http://192.168.1.130:4000/v1/feathers-hooks-common/index.html#fastjoin
