### ISSUE TITLE
Prevent certain fields from being changed

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#145]
This would throw if a patch method (maybe even an update?!?) contained any of a set of field names (dot notation).

This could be useful when combined with `iff` and a role-checking hook to prevent field updates.

**Comment by eddyystop** [comment]
ae [6:39 PM] 
@eddyystop The hooks are straightforward to write, but knowing _which_  hooks to write is more difficult. If someone was to take https://github.com/eddyystop/feathers-starter-react-redux-login-roles/blob/master/server/services/user/hooks/index.js, for example, they’d have a system where anyone authenticated could write the data for any other user via the `patch` method.

It would be very useful to see the hooks setup of an actual production app.

eddyystop [6:40 PM] 
You would need ...
- The iff/when/unless hook
- A hook that checked if the user belonged to one of a list of roles.
- The discard or remove hook used with the above 2.
- A hook that checked if hook.data contained any of a set of fields. Dot notation can be done using the getByDot hook utility.
 
I think that's it. Of course you could spec an api containing an object which is passed to a higher level hook which uses the above mentioned functions.

**Comment by ekryski** [comment]
We should totally do this

**Comment by eddyystop** [comment]
The preventChanges before patch hook is in https://github.com/feathersjs/feathers-hooks-common/pull/175 and will be published in v3.3.0.

The more comprehensive hook detailed above will have to wait until permissions lands.

**Comment by AaronBurmeister** [comment]
What about `preventChanges` in `update`?

**Comment by eddyystop** [comment]
`preventChanges` added for Buzzard.

https://feathers-plus.github.io/v1/feathers-hooks-common/index.html#preventchanges
