### ISSUE TITLE
convert date for db adapters

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#153]
```js
function convertDate(fieldName) {
  return function(hook) {
    const prop = hook.data && hook.data[fieldName];

    if(prop) {
      hook.data[fieldName] = Date().toISOString().slice(0, 19).replace('T', ' ');
    }
    
    return Promise.resolve(hook);
  }  
}
```

**Comment by ekryski** [comment]
Which DB doesn't take ISO formatted dates?

@eddyystop mentioned that this came from an issue from a community member in Slack.

To me, this seems like an edge case with their system. I’ve never run into that across PG, NeDB, SQLite, and Mongo so part of me feels like that is probably just a custom hook someone should be writing if they need it and it doesn't belong as a common hook.

Personally, I'd say we close this and revisit if it comes up frequently. It's so easy/cheap to write hooks that we really should only tackle the common ones that people require. We can't write one for every possible scenario. 😄

**Comment by arlair** [comment]
I came across this and it seems MySQL 5.6 introduced a `STRICT_TRANS_TABLES` `sql_mode` that only allows MySQL formatted dates and not ISO formatted.

Options seem to be disabling `STRICT_TRANS_TABLES`, or formatting dates in a manner like the code above.

See here for an example: https://dba.stackexchange.com/questions/48704/mysql-5-6-datetime-incorrect-datetime-value-2013-08-25t1700000000-with-er

**Comment by eddyystop** [comment]
Consolidated with https://github.com/feathers-plus/feathers-hooks-common/issues/347
