### ISSUE TITLE
Convert fields coming in from query params

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#184]
smixx
Do we have a common hook to convert fields coming in from query params? For example certain fields to booleans, etc. I didn’t see one like that in the docs but I may be missing something. If not, could be useful?

I’ve seen a few people ask, its a pretty simple hook for someone to just write in their project and thats what we’ve typically done

eddyystop
@smixx the `traverse` hook is intended for that

We would have to set up some standards if we wanted to go beyound that. Including when things like `'null'` should not be converted to `null`. (edited)

smixx
OK thanks @eddyystop I’m thinking something even simpler, a one-liner like `convertQueryParamToBool('read')`, thats pretty explicit so it could obviously be more generic and take some options

eddyystop
@smixx Would there be differences between DBs e.g. some would not like a `true` value?

smixx
Those are all the common ones I’ve had to deal with. Most common is string to bool & numbers

**Comment by corymsmith** [comment]
The other one that would be useful is converting a string ID to a Mongo Object IDs. This is particularly useful if you are using the native mongo driver however its Mongo specific and we don't want to have to include the mongo driver. I did see this lib that would do the trick without having to include mongo https://www.npmjs.com/package/bson-objectid but again it may be too DB specific for this repo.

**Comment by eddyystop** [comment]
I was looking into this. The `validateSchema` can coerce data types. Wouldn't that be the logical thing to use as you likely want to do other validation at the same time? https://github.com/epoberezkin/ajv#coercing-data-types

**Comment by eddyystop** [comment]
Consolidating with https://github.com/feathers-plus/feathers-hooks-common/issues/418
