### ISSUE TITLE
Rename hook object to context

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#201]
As a result of this discussion https://github.com/feathersjs/feathers-hooks/issues/159 .

Already started with https://github.com/feathersjs/feathers-hooks-common/pull/200 .

**Comment by daffl** [comment]
To avoid confusion we should make sure that we change it everywhere in the docs (especially https://docs.feathersjs.com/api/hooks.html#hook-objects).

**Comment by eddyystop** [comment]
Changed in lib/, changed in Buzzard docs. Not changed in tests/.
