### ISSUE TITLE
Add some (trivial) Sequelize-oriented hooks

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#210]
I'm thinking of writing some trivial Sequelize hooks, e.g. set `raw` true/false, rehydrate, dehydrate.

**Comment by eddyystop** [comment]
From ryan
``` javascript
function (hook) {
   if (!hook.params.sequelize) hook.params.sequelize = {};
   hook.params.sequelize.raw = true;
   hook.params.sequelize.include = [{ model: hook.app.services[foo].Model }];
}

const hydrate = require('feathers-sequelize/hooks/hydrate');
const dehydrate = require('feathers-sequelize/hooks/dehydrate');

hooks.after.find = [hydrate(), doSomethingCustom(), dehydrate(), someFeathersCommonHook()];```
```

**Comment by eddyystop** [comment]
https://stackoverflow.com/questions/42841810/feathers-js-sequelize-service-with-relations-between-two-models/42846215#42846215

**Comment by eddyystop** [comment]
https://docs.feathersjs.com/api/databases/sequelize.html#working-with-sequelize-model-instances

**Comment by daffl** [comment]
Should ORM specific hooks really be in the "commons" repository though? I always viewed this collection as a "no dependency" collection of hooks.

**Comment by marshallswain** [comment]
It will be weird up until this repo is renamed to feathers-hooks.

**Comment by eddyystop** [comment]
I was thinking to perhsps add these to feathers-community-hooks

**Comment by eddyystop** [comment]
Consolidating this with https://github.com/feathers-plus/feathers-hooks-common/issues/347

**Comment by jjdonov** [comment]
@eddyystop sorry for commenting on a closed issue but your comment references the exact issue I am having right now:

> The result of a raw query (using sequelize) looks like this:
>
 > id: 123,
  comment_text: "Foo bar",
  user.id: 789,
  user.name: "Joe",
  user.email: "joe@schmoe.com"
}
>Whereas it should look like this:
>
  >id: 123,
  comment_text: "Foo bar",
  user: {
    id: 789,
    name: "Joe",
    email: "joe@schmoe.com"
  }
}```


What's the solution here? In my particular example, I have a one to many relationship between `user` and `membership` table and I'd like the `memberships` to be populated as an array in the result. Instead, I end up with two `user`s returned, each with a different `membership` values.

I am setting it in a before hook on the user service.
```
const includeMembership = async (context) => {
  const UserMembershipModel = context.app.service('userMembership').Model;
  context.params.sequelize = {
    include: [{model: UserMembershipModel}],
    //raw: false
  };
  return context;
};
```

If I use`raw: false` the payload looks like I'd expect, but that breaks other things. (The object is assumed to be a plain old object downstream).

**Comment by eddyystop** [comment]
You should speak to ryan.wheale on the slack forum.
