### ISSUE TITLE
populate: Using a function for schema

### ISSUE THREAD

**Issue by Torge** [feathers-plus/feathers-hooks-common#214]
### Steps to reproduce
I was trying to use a function for schema (see https://auk.docs.feathersjs.com/api/hooks-common.html#selecting-schema-based-on-ui-needs)

```
const schemas = {
  'bar': {
    schema: {
      include: [
        {
          service: 'bar',
          nameAs: 'bar',
          parentField: 'barId',
          childField: '_id',
        }
      ]
    }
  }
};
...
before: {
    all: [client('schema')]
  },

  after: {
    all: [populate(() => schemas[hook.params.schema])]
  },
```
But I get this Error, when starting the app
```
Error: Options.schema is not an object. (populate)
at exports.default (/home/torge/src/feathers-sandbox/node_modules/feathers-hooks-common/lib/services/populate.js:23:11)
    at Object.<anonymous> (/home/torge/src/feathers-sandbox/src/services/foo/foo.hooks.js:25:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/torge/src/feathers-sandbox/src/services/foo/foo.service.js:4:15)
```
### Expected behavior
In the docs it says that the populate hook accepts a function for shema, but it doesn't.

### System configuration
**Module versions** (especially the part that's not working):
"feathers": "^2.1.3",
"feathers-hooks-common": "^3.5.1",

**NodeJS version**:
v7.7.2

**Operating System**:
ubuntu 16.10

**Module Loader**:
npm 4.1.2

**Comment by eddyystop** [comment]
The docs say `schema` may be a function, you however are making `object` a function. Use `populate({ schema: () => {} })`.

**Comment by Torge** [comment]
Thanks for the reply.

I got confused, because of this example in the docu:
```
purchaseOrders.after({
  all: populate(() => poSchemas[hook.params.schema])
});
```
Shouldn't it look like this:
```
purchaseOrders.after({
  all: populate({ schema: () => poSchemas[hook.params.schema] })
});
```

**Comment by eddyystop** [comment]
I guess that depends on what's in `hook.params.schema` but, at a minimum, the name is confusing.

**Comment by Torge** [comment]
I just found this old issue of mine, but it is already resolved, so i'm closing it. Thanks
