### ISSUE TITLE
hook to increment a value

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#226]
for keys in some db

**Comment by daffl** [comment]
Another useful hook - you will need it for this as well - would be a before hook that retrieves the old record(s) and adds it as `hook.original`. Currently hooks that need the original record (like the ones checking for permissions, making a diff or changing a dependant value) all do that themselves which may cause unnecessary database calls.

**Comment by eddyystop** [comment]
https://docs.feathersjs.com/api/hooks-common.html#stashbefore has beaten you to it.

**Comment by daffl** [comment]
Ha! I should've checked first :D Nice work.

**Comment by eddyystop** [comment]
`alterItems` can be used for incrementing values.
