### ISSUE TITLE
Cancelling further hooks

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#236]
Setting `context.result` prevents the DB call. It does not prevent the remaining before & after hooks from running.

Can we help to prevent hooks running?

You could set hook.cancelled = true and then wrap everything that should into a iff hook checking iff(hook => hook.cancelled, otherHooks)

**Comment by beeplin** [comment]
#355

**Comment by eddyystop** [comment]
Consolidate in 355
