### ISSUE TITLE
SoftDelete Hook still called twice

### ISSUE THREAD

**Issue by TheSinding** [feathers-plus/feathers-hooks-common#238]
After some debugging with @eddyystop 
We found that the SoftDelete hook is still called twice for some reason.

Test setup was a brand new app and a service generated with the CLI. Then just added the hook in before.all

feathers-hooks-common v3.6.1
feathersjs cli v2.3.0

**Comment by eddyystop** [comment]
I won't be able to adress this for a while. It would be critical only for high load servers.

**Comment by eddyystop** [comment]
`softDelete2` is a noteable improvement over `softDelete`. It will be released later this week once its docs are complete.

softDelete2 has an option to either run a probing `get` on a get call, or to run just a single get.

I'll close this issue. Feel free to reopen one for softDelete2 if you still have an issue.
