### ISSUE TITLE
Does context.result = null skip remaining hooks? 

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#240]
https://github.com/feathersjs/feathers/issues/635#issuecomment-320175896

What I can tell is that in my case I use a before hook to check for permissions. When the check fails on a create for instance I throw an error and set the result to null. Don't know which of both things does the job (or if it is actually a mix) but the object is not created in DB neither other hooks are ran.

If so, mention in docs. Consider a util or hook to do this.

**Comment by daffl** [comment]
Setting `hook.result` will only skip the service call. We could add a section that mentions that you have to wrap hooks that you want to be skipped in that case into a `iff(context => context.result !== undefined, myHook)`.

**Comment by beeplin** [comment]
#355

**Comment by eddyystop** [comment]
Consolidate in 355
