### ISSUE TITLE
serialize for Sequelize

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#245]
A Sequelize-specific hook like `serialize` is possible using something like https://github.com/hauru/sequelize-to-json

**Comment by daffl** [comment]
Is that what the [hydrate hooks](https://github.com/feathersjs/feathers-sequelize/tree/master/hooks) are doing?

**Comment by eddyystop** [comment]
I believe they convert between ORM and POJO objects.

I wonder if Sequelizer caches decisions given a set of includes. If it doesn't, at least some SQL databases cache their strategy decisions for reuse. In such a case there could be a benefit in reusing a set of includes even if they return more data than needed vs customizing for every case. Should that be true, the proposed hook could be useful.

**Comment by eddyystop** [comment]
Consolidating rfelated discussions in https://github.com/feathers-plus/feathers-hooks-common/issues/347
