### ISSUE TITLE
pluck: Always pluck regardless of provider

### ISSUE THREAD

**Issue by dschnare** [feathers-plus/feathers-hooks-common#252]
### Steps to reproduce

1. Create a simple feathers app (use the guide)
2. Use the pluck hook to pluck some properties during a before:create

```
before: {
  create: [
    pluck('prop1', 'prop2')
  ]
}
```  

3. Make a call on the server to create a record with valid properties and extra properties

```
myService.create({ prop1: 1, prop2: 2, prop3: 3: prop4: 4 })
```

### Expected behavior
Expected the pluck hook to always pluck properties from the data items. Thereby removing extra
properties.

### Actual behavior
pluck only plucks properties iff the service method was called by a client.

### Proposed Solution
Use composition instead of baking this functionality inside of pluck (i.e. dog food the other common hooks). This makes pluck far more useful.

*Currently:*
```
  // This plucks iff the service call was made by a client
  pluck('prop1', 'prop2')
```

*Instead:*
```
  // This would replicate the current behviour of pluck (if pluck had the provider check removed from its implementation)
  when(
    isProvider('external'),
    pluck('prop1', 'prop2')
  )
```

I realize this a breaking change, but without this change pluck is useless outside of external service calls.

**Comment by eddyystop** [comment]
"ProTip: This hook will only fire when params.provider has a value, i.e. when it is an external request over REST or Sockets." So this is the spec'ed behaviour for pluck and it would cause too many problems to change it.

I suggest you make a modified copy of this hook for your needs.

**Comment by bertho-zero** [comment]
I agree with @dschnare for avoiding magic logic in hooks.

**Comment by eddyystop** [comment]
We deprecated `remove`s magic with `discard`. We'd have to use a name change also for `pluck`.

**Comment by eddyystop** [comment]
The `pluck` and `pluckQuery` hooks have been deprecated in the Feathers Buzzard version in favor of `keep` and `keepQuery`. The latter hooks have no magic.

https://feathers-plus.github.io/v1/feathers-hooks-common/index.html#keep

https://feathers-plus.github.io/v1/feathers-hooks-common/index.html#Migrating-from-Auk-to-Buzzard
