### ISSUE TITLE
iff doesn't bind hook functions to service instance

### ISSUE THREAD

**Issue by j2L4e** [feathers-plus/feathers-hooks-common#258]
when hooks are called by the iff function `this` is not bound to the service the hook was run on.

### Steps to reproduce

```
app.service('myService').hooks({
  before: {
    all: {
      function (hook) {
        console.log(this === hook.app.service('myService'));
      },
      iff(() => true, function (hook) {
        console.log(this === hook.app.service('myService'));
      }),
    }
  }
});
```

prints
```
true
false
```

**Comment by eddyystop** [comment]
That is documented in the API. Please use `hook.service` instead.
"This The predicate and hook functions in the if, else and iffElse hooks will not be called with this set to the service. Use hook.service instead."

We have not found a way to pass the expected `this` to the hook function, if there is a way to do so.

**Comment by daffl** [comment]
Wouldn't this just be changing https://github.com/feathersjs/feathers-hooks-common/blob/master/src/common/iff.js#L7 to

`[].concat(...trueHooks.map(h => h.bind(this))), null)`

?

**Comment by eddyystop** [comment]
Maybe, I tried code of that nature.

This also needs to be addressed https://github.com/feathersjs/feathers-hooks-common/blob/master/src/common/iff.js#L9

Perhaps j2L4e can make such changes, try them and write some tests if he gets it to work. I've already spent too much time on this in the past.

**Comment by eddyystop** [comment]
I think we can close this.
