### ISSUE TITLE
Preserve createdAt on updates

### ISSUE THREAD

**Issue by ribaptista** [feathers-plus/feathers-hooks-common#264]
Hello

I'm using hook `setNow` to automatically set `createdAt` on creation.
My issue is that on updates field `createdAt` is removed (since update operations replace entire object). 
This is what I'm currently doing to prevent updates from removing (or changing) `createdAt`:

```javascript
app.hooks({
  before: {
    create: [setNow('createdAt', 'updatedAt')],
    update: [
      preserveCreatedAt,
      setNow('updatedAt')
    ]
  }
});

function preserveCreatedAt(hook) {
  return hook.service.get(hook.id).then(obj => {
    hook.data.createdAt = obj.createdAt;
  });
}
```

Is there a better way of preventing `createdAt` from being changed/removed by further updates?

Thanks!

**Comment by bertho-zero** [comment]
You should use `patch` instead of `update`, I think.

**Comment by ribaptista** [comment]
@bertho-zero 
I see fields like `createdAt`, `updatedAt`, `createdBy` and `updatedBy` as metadata fields about the entity, thus client requests should not be able to change them despite using `patch` or `update`.

**Comment by eddyystop** [comment]
Yes, you should use patch. You can use the common hook `preventChanges` to prevent patch from changing given field names.
