### ISSUE TITLE
devDependencies packages in package-lock.json

### ISSUE THREAD

**Issue by sonycamera** [feathers-plus/feathers-hooks-common#267]
It seems that package-lock.json was generated under 'npm install' rather than 'npm install --only=production". I think the later one is better, or just remove the package-lock.json

**Comment by eddyystop** [comment]
Can't run the rests with your suggestion. I'm not even sure travis could run them.

There is no real downside to having extra modules in node_modules on the server. First, its only disk space. Second, other packages may be using the modules for production.

There is no advantage to be gained for client bindles as they merge only what is being used.
