### ISSUE TITLE
Error while using disallow

### ISSUE THREAD

**Issue by neerajincaendo** [feathers-plus/feathers-hooks-common#272]
Hello ,
i have service order which i want to access only from server so i use 
`disallow('external')`
so before that i have used `hook.params.provider = 'server'` which is rest before .
but while calling create order ,  i am getting error `Provider 'server' can not call 'create'. (disableMethod) `.

Please suggest the solution ASAP.

**Comment by eddyystop** [comment]
`hook.params.provider` should be `undefined` for the server. Would be the cause of your issue? If not, please provide the `service.hooks.before` you have configured.
