### ISSUE TITLE
Yarn add can not find this package

### ISSUE THREAD

**Issue by locosoft1986** [feathers-plus/feathers-hooks-common#288]
### Steps to reproduce

1.Initialize a new node project by feathers generate app.  After it will create new project which use @feathersjs/feathers package.
2. Run “yarn add feathers-hooks-common”,after awhile when it completed the actual package that is installed is from the old feathersjs/feathers-hooks-common. The package is from “https://www.npmjs.com/package/feathers-hooks-common” and its readme file is not the same as in this repo.

### Expected behavior
yarn add feathers-hooks-common,the package should point to this repo.

### Actual Behavior 
After yarn add, the package points to the old feathers js one.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

yarn 1.3
Node 8.9.1

**Comment by eddyystop** [comment]
The repo published on npm is v3.10.0, the last version for Feathers Auk. The repo on the main branch of GitHub is what's waiting to be published for Feathers Buzzard, and will be v4.0.0. on npm.

Until its published, you can get load v4.0.0 with `"feathers-hooks-common": "git://github.com/feathers-plus/feathers-hooks-common.git#master"` in package.json.

BTW, the docs are 90% rewritten at https://feathers-plus.github.io/v1/feathers-hooks-common/

You may want to look at fastJoin. Its an alternative to populate which makes roughly 10% of the service calls populate makes.

Please feel free to reopen this issue if necessary.
