### ISSUE TITLE
How do I install v4?

### ISSUE THREAD

**Issue by otang** [feathers-plus/feathers-hooks-common#305]
![image](https://user-images.githubusercontent.com/800081/33189928-86e84742-d05c-11e7-93ea-9dca3b11f82f.png)

### Expected behaviour
There is a v4.x.x release, branch, or tag.

### Actual behavior
The latest release is 3.10.0

**Comment by eddyystop** [comment]
You can read the first section in the guide `Usage`. :)

https://feathers-plus.github.io/v1/feathers-hooks-common/index.html
