### ISSUE TITLE
Headers info is removed which makes custom API KEY authorization impossible

### ISSUE THREAD

**Issue by roelvan** [feathers-plus/feathers-hooks-common#306]
Code responsible:
https://github.com/feathers-plus/feathers-hooks-common/blob/9e00226d2bb2b614f4c342a64f6cd3b705dd2a95/lib/services/soft-delete.js#L59-L63
So you cannot create a [Custom API Key Auth Strategy](https://docs.feathersjs.com/guides/auth/recipe.custom-auth-strategy.html#creating-a-custom-api-key-auth-strategy)

**Comment by roelvan** [comment]
Following the guide I had to change this to make it work:
```
iffElse(
      // if the specific header is included
      ctx => !ctx.params.authenticated && ctx.params.headers['x-api-key'], // THIS LINE
      // authentication with this strategy
      auth.hooks.authenticate('apiKey'),
      // else fallback on the jwt strategy
      auth.hooks.authenticate(['jwt'])
    )
```

**Comment by subodhpareek18** [comment]
I've written these middlewares to get the headers where I want them.

```js
export const rest = () => (req, res, next) => {
  req.feathers = {
    ...req.feathers,
    headers: req.headers,
    origin: req.get('origin')
  };
  next();
};

export const socketio = () => (socket, next) => {
  socket.feathers = {
    ...socket.feathers,
    headers: socket.handshake.headers,
    origin: socket.handshake.headers.origin
  };
  next();
};

export default {
  rest,
  socketio
};
```
```js
app.use(middleware.headers.rest());
app.configure(
  socketio(io => {
    io.use(middleware.headers.socketio());
  })
);
```

**Comment by eddyystop** [comment]
@roelvan Thanks for the info. I plan to allow injection of a custom function to create the context.params. I'll likely include your suggestion in the default.

**Comment by thngdude** [comment]
I've come across this issue, too. Is there a reason the headers are still not included in the gist posted by @roelvan in updates that followed?

**Comment by eddyystop** [comment]
softDelete is being rewritten. You will be able to provide your own function for the probe GET.

**Comment by thngdude** [comment]
@eddyystop Thanks ... I've written my own softDelete for now that includes the header. I'm wondering what was the logic of excluding it in the first place. Not challenging. Just curious whether there was a reason to actively not include it.

**Comment by eddyystop** [comment]
`softDelete2` is a noteable improvemant over `softDelete`. It will be released later this week once its docs and written.

I think we can close this issue now.
