### ISSUE TITLE
[feature request] alterItems allows async func?

### ISSUE THREAD

**Issue by beeplin** [feathers-plus/feathers-hooks-common#307]
Now alterItems only works for sync func. Sometimes we need another `alterItemsAsync` to handle async funcs.

**Comment by eddyystop** [comment]
Could an IIFE async/await be used?
```js
alterItems(rec => {
  rec.userRecord = (async () => await service.get() )()
})
```

**Comment by eddyystop** [comment]
Handled by https://github.com/feathers-plus/feathers-hooks-common/pull/313

@beeplin please let me know if there are any issues.

**Comment by eddyystop** [comment]
Documentation updated.
