### ISSUE TITLE
consider a new `disableMultiItemCreate` just like `disableMultiItemChange`?

### ISSUE THREAD

**Issue by beeplin** [feathers-plus/feathers-hooks-common#308]
just to check if Array.isArray(context.data)

**Comment by eddyystop** [comment]
Maybe also rename disableMultiItemChange to disableMultiItemOatch for clarity.

**Comment by beeplin** [comment]
Made a PR #330 on this.

BTW I am afraid that renaming `disableMultiItemChange ` to `disableMultiItemPatch` is kind of too much -- it works for not only `patch` but also `remove`. And, renaming a hook is a breaking change, and it seems not worth it. :)

**Comment by eddyystop** [comment]
You're right on the name. I forgot about remove.
