### ISSUE TITLE
fastJoin and pagination

### ISSUE THREAD

**Issue by dottodot** [feathers-plus/feathers-hooks-common#314]
I'm just trying to get my head around  fastJoin and when I follows the examples in the documentation is doesn't work, the only way I get it to work is to make the request with `paginate:false`  like the example below. Is it because the documentation is based on services not having pagination turned on or am I'm missing something.

```
module.exports = {
  before: context => {
    context._loaders = { image: {} };
    context._loaders.image._id = new BatchLoader(
      async (keys, context) => {
        const result = await context.app.service('image').find(
          makeCallingParams(
            context,
            {
              _id: { $in: getUniqueKeys(keys) },
              $select: ['key', 'version'],
              $sort: {
                weight: 1
              }
            },
            null,
            { paginate: false }
          )
        );

        return getResultsByKey(keys, result, image => image._id, '!');
      },
      { context }
    );
  },

  joins: {
    image: () => async (post, context) =>
      (post.image = await context._loaders.image._id.load(post.image)),
    template: () => async (post, context) =>
      (post.template = await context._loaders.image._id.load(post.template))
  }
};
```

**Comment by eddyystop** [comment]
Yes the examples assume no pagination. I'll add a note to both the guide and API.

The syntax of the API does not allow us to assume paginate: false. It may be quite intrusive to have makeCallingParams default to that.

**Comment by dottodot** [comment]
Ok that's fine just wanted to make sure I wasn't missing something. Whilst your updating there's a minor typo in batch loaders

```
const BatchLoader = require('@feather-plus/batch-loader');
```
should be (missing the s on feathers)
```
const BatchLoader = require('@feathers-plus/batch-loader');
```

**Comment by eddyystop** [comment]
Thxs.
