### ISSUE TITLE
isProvider returning wrong value

### ISSUE THREAD

**Issue by Creiger** [feathers-plus/feathers-hooks-common#315]
### Steps to reproduce

I am not sure if it is bug or not. I am querying a service inside a middleware in some intervals. It starts few seconds after the app is launched. Lets call it "internal check". I am using isProvider hook to enable authentication only for external providers.

BUT if i use this service via socketio before the first inernal check is made, the provider in this internal check hook is set to socketio thus authentication is required and it fails. And every next internal check has this wrong provider.

If i wait for the first internal check and query the service via socketio after, it is ok. External query is authenticated and every next internal check has undefined provider, so it does not authenticate.

### Expected behavior
It should always return undefined when service is used inside app.

### Actual behavior
It is returning last provider value.

**Comment by eddyystop** [comment]
isProvider checks the `context.provider` passed to the hook on every call. It has no control over what that value is set to.

Calling services from within middleware is not typical, so I do not know what the ramifications are. I believe one thing to watch out for is services are only ready after `app.listen()` is run. 

I believe I've seen you have already asked a question concerning calling services in middleware. I think this question belongs there for the reason first mentioned.

I'll watch that conversation. Thanks.

**Comment by eddyystop** [comment]
I think we can close this now.
