### ISSUE TITLE
makeCallingParams include not working

### ISSUE THREAD

**Issue by Mattchewone** [feathers-plus/feathers-hooks-common#334]
### Steps to reproduce

Include something from the existing params and this will not be included in the calling context for the service call. 

### Example
```js
context => {
  context.app.service('user').find(makeCallingParams(
    context,
    { name: 'something' },
    ['provider', 'authenticated', 'user']
  )).then(response => {
    context.result = response
    return context
  })
}
```

Looking here - https://github.com/feathers-plus/feathers-hooks-common/blob/master/lib/services/make-calling-params.js#L9
It is testing whether those to be included exist on the top level context rather than the `context.params` so maybe we could add the `getByContext` to get the value from the existing context and add that to the new context.

**Comment by eddyystop** [comment]
I assume you mean to refer to existsByDot and getByDot, in which case I agree with you.

**Comment by Mattchewone** [comment]
Yes sorry I meant `getByDot`. I shall put together a PR if you would like?
