### ISSUE TITLE
support for context.dispatch

### ISSUE THREAD

**Issue by beeplin** [feathers-plus/feathers-hooks-common#340]
Buzzard introduces the new `context.dispatch`:

![image](https://user-images.githubusercontent.com/13058150/35363156-8d795cb8-01a3-11e8-9fc3-3aed70036e90.png)

Currently our hooks in this repo are not aware of the existence of `context.dispatch`, so if some previous hooks set `context.dispatch`, our hooks still focus on reading\writing `context.result` which is actually not sent to the client.

For example, for after hooks, `keep` followed by `protect`(which set `context.dispatch` https://github.com/feathersjs/authentication-local/blob/master/lib/hooks/protect.js) still modify `context.result` instead of `context.dispatch`.

**Comment by eddyystop** [comment]
Noted.

The common hooks presently concern themselves with the hook chain and the service call, hence context.result.

context.dispatch seems like a parallel output path heading someplace else. I understand its benefit, but I find it confusing from high level design view.

How do you suggest **every** hook decide if it should use context.rseult or context.dispatch ?

**Comment by eddyystop** [comment]
Any ideas?

**Comment by eddyystop** [comment]
What do you think of the following syntax:
```js
discard{'password') // like now, discards in content.data (before) or context.result (after)
useDispatch(discard('password'), hook2, ...) // discards in context.dispatch
useData(discard('password'), ...) // discard in context.data only
useResult(discard('password'), ...) // discard in context.result only
```
We can extend this should there be a way to set what id sent on a service event.

The simplest way to implement this is with by, say, useDispatch setting context.params.__hooksUse === 'displatch' and having get-items and replace-items check that.

However this wouldn't work if a hook calls another hook or calls a service with hooks. We would have to maintain an array for __hooksUse. And even then, the array may become corrupted if a hook throws an error.

Still this syntax is an idea to consider.

**Comment by beeplin** [comment]
@eddyystop sorry for the delayed reply. I got a really bad flu in the past few weeks, and then it comes Chinese New Year vacation~

I share the same feelings with you that, `context.dispatch` might not be a very neat design. It is currently used in some hooks from core packages (like `protect` hook in `@feathersjs/authentication`), and it seems that it is introduced only for sending results to client. However, in the old days, hook writers could always check `context.params.provider` when determining what to be sent to client, and  what to local server. `context.dispatch` might be over designed, I think.

I don't think maintaining a `context.params.__hookUse` list is the best way to go. It would be easier to modify each common hook and to add corresponding judgement code.

But in fact I guess the best way to dealing with this issue is to --- persuade our core team to give up the `context.dispatch` design :)))

**Comment by eddyystop** [comment]
Influenza is a serious disease, my mother died from it.

One complexity is that a hook may set both context.result and context.dispatch. One to return to the caller, the other to return as an event to other clients. I'm not convinced the hook can avoid explicitly knowing which it should modify.

I agree the __hookUse array is a bad idea. It may be possible maintain a `params._useWhat = 'dispatch'`. The useDispatch hook would cache the current params._useWhat in its closure, set it to 'dispatch', and call the hooks (like iff does). On successful completion, useDispatch restores the cached value.

- if a hook called with 'dispatch' calls a common hook, that called hook would work with 'dispatch' and get/setItems should use the right data.
- there may be issues if a hook called with 'dispatch' calls a custom hook which does not use get/setItems.
- on throw, we don't care about params._useWhat
- on SKIP, we don't care

Can you think of an edge case where this would not work?

**Comment by beeplin** [comment]
Yes I realized my previous understanding of context.dispatch is wrong. For rest connection it is not necessary, but when using socketio, a locally called service method may return context.result to the local call, while at the same time dispatch context.dispatch to the socketio connections.  This is actually a proper design.

And using closure to cache each hook's params._useWhat is a wonderful idea. I agree this is the right way to go.

**Comment by eddyystop** [comment]
Would you give `actOnDispatch(...hooks)` and `actOnDefault(...hooks)` a try? They've been pushed to GitHub (along skipRemainingHooks) but not yet published to npm.

tests/services/act-on.test.js shows how they're used.

 `getItems` and `replaceItems` have also been modified to support actOn*

**Comment by beeplin** [comment]
As far as I tested it works wonderfully. The only thing is that we should double-check that all the common hooks that might dealing with `context.dispatch` are all using `getItems/replaceItems` instead of accessing data directly.

**Comment by eddyystop** [comment]
Thanks for checking it out.

I was rigorous about using get/replaceItems and there have been only 2 contributed hooks.

**Comment by eddyystop** [comment]
docs updated.

v4.8.0 published on npm.
