### ISSUE TITLE
fix replaceItems

### ISSUE THREAD

**Issue by abhisekp** [feathers-plus/feathers-hooks-common#341]
`isDone` always `undefined` as `replaceItems` doesn't contain any `return` statements.

https://github.com/feathers-plus/feathers-hooks-common/blob/master/lib/services/alter-items.js#L30

**Comment by eddyystop** [comment]
`alterItems` was enhanced to support an async `func`. The resolution of the async call was originally developed in `replaceItems` to implement a generatized solution.

This was later changed to a design where `func` had to resolve the items itself, via `await` or `.then()`. The `isDone` was not cleaned up during this change.

Thanks for the catch.

**Comment by eddyystop** [comment]
https://github.com/feathers-plus/feathers-hooks-common/pull/354

Published to npm as v4.5.5
