### ISSUE TITLE
How to use getResultsByKey when querying a field with array of ids

### ISSUE THREAD

**Issue by dottodot** [feathers-plus/feathers-hooks-common#358]
In the following Batchloader I'm querying products which contains an array of ids and I get a result, the part I can't work out is `getResultsByKey` as the join has an empty result. I'm assuming it's `getRecordKeyFunc` that I've got wrong but not really sure what I should be returning in this situation.

```
    context._loaders.items.products = new BatchLoader(
      async (keys, context) => {
        const result = await context.app.service('item').find(
          makeCallingParams(
            context,
            {
              products: { $in: getUniqueKeys(keys) },
              $select: ['title', 'products']
            },
            null,
            { paginate: false }
          )
        );
        console.log(result); // This part works
        return getResultsByKey(keys, result, item => item.products, '[!]', {
          defaultElem: []
        });
      },
      { context }
    );
```

**Comment by eddyystop** [comment]
`item.products` is plural. Is it an array? `getResultsByKey` expects
- Its `keys` param to be an array of strings or numbers, each being a record key.
- its `getRecordKeyFunc` to return a string or number which matches one of the `keys` elements.

Let me know if `item.products` is an array. I'll see what can be done.

Otherwise give me a sample `keys` and `results`.

**Comment by dottodot** [comment]
yes `item.products` is an array so in my mongoose schema it looks like

```
const item = new Schema(
    {
      products: [
        {
          type: ObjectId,
          ref: 'product'
        }
      ],
    },
    {
      timestamps: true
    }
  );
```

**Comment by eddyystop** [comment]
I think this issue can be closed now. Feel free to reopen it.
