### ISSUE TITLE
fastjoin strange results, $sort not respected

### ISSUE THREAD

**Issue by dottodot** [feathers-plus/feathers-hooks-common#359]
Not sure if I'm doing something wrong or if there is a bug but in the following the log of the productcolour find result is in the correct order i.e sorted by weight, but in the hook.result they are ordered as they appear in the ObjectID array

```
module.exports = {
  before: context => {
    context._loaders = { colours: {} };

    context._loaders.colours._id = new BatchLoader(
      async (keys, context) => {
        const result = await context.app.service('productcolour').find(
          makeCallingParams(
            context,
            {
              _id: { $in: getUniqueKeys(keys) },
              $select: ['title', 'swatch', 'gradients', 'weight'],
              $sort: {
                weight: 1
              }
            },
            ['user', 'schema'],
            { paginate: false }
          )
        );
        console.log('colours', result);
        return getResultsByKey(keys, result, colour => colour._id, '!');
      },
      { context }
    );
  },

  joins: {
    colours: () => async (post, context) =>
      !post.colours
        ? null
        : (post.colours = await context._loaders.colours._id.loadMany(
            post.colours
          ))
  }
};
```

**Comment by eddyystop** [comment]
Please see what the result is of the `makeCallingParams`. If its as expected, then the issue would be with the adapter.

Otherwise we'll look into it more. Thanks.

**Comment by eddyystop** [comment]
I need to ask you, where are the results not sorted as you expect? After getResultsByKey or after await context._loaders.colours._id.loadMany?

**Comment by dottodot** [comment]
It the getResultsByKey where the sort is wrong. So in the follow `result` is in the right order but `test` isn't. The empty string also makes no difference.

```
context._loaders.colours._id = new BatchLoader(
      async (keys, context) => {
        const result = await context.app.service('productcolour').find(
          makeCallingParams(
            context,
            {
              _id: { $in: getUniqueKeys(keys) },
              $select: ['title', 'swatch', 'gradients', 'weight'],
              $sort: {
                weight: 1
              }
            },
            ['user', 'schema'],
            { paginate: false }
          )
        );
        console.log(result);
        const test = getResultsByKey(
          keys,
          result,
          colour => colour._id + '',
          '!'
        );
        console.log(test);
        return test;
      },
      { context }
    );
```

**Comment by eddyystop** [comment]
`getResultsByKey` is supposed to return an array of results, where the n-th element of that result array is the  result for the n-th element of `keys`.
```js
keys = [1, 5, 2, 4, 3];
getResultsByKey(..., keys, ...) // [result-for-1, result-for-5, result-for-2, ...]
```
The `'!'` indicates you expect a single object for each key, so you'll get
```js
getResultsByKey(..., keys, ...) // [ { result-for-1 }, { result-for-5 }, { result-for-2 }, ...]
```
The `await context._loaders.colours._id.loadMany(post.colours))` is a convenience short cut for
```js
 [
  await context._loaders.colours._id.load(post.colours[0])),
  await context._loaders.colours._id.load(post.colours[1])),
  ...
]
```
So you will get an array of results ordered by `post.colours`.

**Comment by eddyystop** [comment]
If you are looking for `await context._loaders.colours._id.loadMany(post.colours))` to return an array sorted by `weight`, then this is not the way to do it.

**Comment by dottodot** [comment]
OK think I've misunderstood how it all works. So should just do those sort of joins like

```
module.exports = {
  joins: {
    colours: () => async (post, context) =>
      !post.colours
        ? null
        : (post.colours = await context.app.service('productcolour').find({
            paginate: false,
            query: {
              _id: { $in: post.colours },
              $select: ['title', 'swatch', 'gradients', 'weight'],
              $sort: {
                weight: 1
              }
            }
          }))
  }
};
```

**Comment by eddyystop** [comment]
I believe that will give you the results are are looking for.

You will however have no caching. That wouldn't affect performance here because `colours:` is at the top level of `joins:`.

It would be slower than the batchloader example if `colours` was not at the top level. In that case I would have suggested your initial batchloader code, but sort the results by `weight`, using `.sort()`, after the `await context._loaders.colours._id.loadMany(post.colours))`.

**Comment by dottodot** [comment]
I haven't got round to setting up caching yet as not got my head round it, so probably makes no difference at the moment, but my original setup does now work if I use `.sort()`, and I understand how Batchloaders work a bit better now too, so thanks.

**Comment by eddyystop** [comment]
The batchloader caches automatically. It will never ask for the same key twice during one fastJoin.
