### ISSUE TITLE
How to filter fastjoin datas

### ISSUE THREAD

**Issue by amuchembled** [feathers-plus/feathers-hooks-common#360]
Hello,

I've make two test services : 
- Countries :
   - Label
- Cities 
   - Label
   - countries_id

In order to get the country label, when calling the cities endpoint, i've used fastjoin which works very well.

But my question is : How do I filter my request by passing a label value instead of an object ID ?

Example : 
FROM : GET /cities?countries_id=1234...
TO : GET /cities?countries.label="Paris" (or something like that)

Thanks for your help !

**Comment by eddyystop** [comment]
You do not mention if you want to use BatchLoaders or not. I'll assume not. Both records have a label field. I'll assume you want to join using them.

```js
module.exports = {
  joins: {
    colours: (...args) => async (city, context) => {
        city.country = await context.app.service('countries').find({
            query: { label: city.label }, paginate: false
        })
    }  } };
```

**Comment by amuchembled** [comment]
Thanks for your answer, but this is not really what I wanted, I think.

Let me give you a more precise example :

A countries document :
{
   id: "1234",
   label : "France"
}

A cities document :
{
   id: "5678",
   label : "Paris",
   countries_id: "1234"
}

When I make a get rest query to "/cities", i want to get the label of the country, populated thanks to fastjoin. Which works great by joining with the ids, in an "after all" hook.

I get something like that as a result :
{
   id: "5678",
   label : "Paris",
   country: {
       id: "1234",
       label : "France"
   }
}

But my real problem now, is to be able to filter this result by selecting a specific country label (from Postman for example).

Ex : GET /cities?countries[label="France"]

Is it possible ?

I've remarqued that populated fields are not known, to the query selector, I can only filter by "countries_id", which is not very sexy to use.

I dont use batchloaders at the moment

**Comment by eddyystop** [comment]
How would you code that using normal Feathers services, without fastJoin?

**Comment by amuchembled** [comment]
I have no idea :/

**Comment by eddyystop** [comment]
Let me know when you do. Then we can map it to fastJoin. Perhaps you can
post the issue to feathersjs/feathers or ask on Slack.

On Thu, Feb 15, 2018 at 1:10 PM, Amaury Muchembled <notifications@github.com

**Comment by eddyystop** [comment]
I think you can get the results you want with  GET /countries[label="France"]?cities
