### ISSUE TITLE
`mongoKeys` can also used in `before` `update/patch/remove`

### ISSUE THREAD

**Issue by beeplin** [feathers-plus/feathers-hooks-common#361]
Glad to see the new `mongoKeys` hook. That is what I always need since I transfered from `mongoose` to vanilla `mongodb`.

I will try using it to see if it can be improved. But at the first glance I can figure out that this hook can also be used before `update/patch/remove`. These three methods can also have `context.params.query` when `context.id === null`, and they do the exactly same thing as `find` does.

**Comment by eddyystop** [comment]
Good point. Thank you.
