### ISSUE TITLE
validateSchema with type: array

### ISSUE THREAD

**Issue by rybaczewa** [feathers-plus/feathers-hooks-common#364]
I want my service to be validated against json schema. Let's say my object schema looks like this:
```json
{"name": "string"}
```
I want the service to only allow Array of said objects, so schema I pass to `validateSchema` looks like this:
```json
{
  "type": "array",
  "items": {"name": "string"}
}
```

Passing object like this:
```json
[{"name": "foobar"}]
```
thows an error `"errors": ["should be array"]`

Looking at source code I've found out is that `validateSchema` hook, if single object is passed, pushes it into list. So for my case to work I need to pass single object schema do `validateSchema` and send array of objects to service. That looks a bit counter-intuitive for me.
https://github.com/feathers-plus/feathers-hooks-common/blob/20eddd420cb4e1b14929ecb7564c6cce5207de26/lib/services/validate-schema.js#L19

I've got two problems with that:
1) It looks like I am unable to allow arrays only by just using jsonSchema, additional code is required
2) I couldn't find above behaviour documented anywhere. I don't see it [here](https://feathers-plus.github.io/v1/feathers-hooks-common/#validateschema)

**Comment by eddyystop** [comment]
`validateSchema` uses the popular `https://github.com/epoberezkin/ajv`. Please look at its docs.

There are also good tutorials such as https://code.tutsplus.com/tutorials/validating-data-with-json-schema-part-1--cms-25343

This is mentiuoned in the API docs.

**Comment by rybaczewa** [comment]
I am aware of `ajv`. Data I push to service isn't validated as a single object against given schema though. Isn't that only becuase of mapping done inside hook?

I expected validation like this:
```schema => object
schema => array
```
But what happens is:
`schema => [object]`
`schema => array`

That causes problem if root object schema is of array type. With array schema it expects array of array objects instead of exact schem match.

**Comment by eddyystop** [comment]
validateSchema validates data in before (or after) hooks in Feathers services. Such data is always an object or an array of objects. It will always assume an array contains object elements each of which need to be validated.

You will have to reformat any other type of structure into one of the above formats.

**Comment by eddyystop** [comment]
I think I realize what the confusion is now. The schema you provide is the schema for the object, not for an array containing the objects. I should have caught on to that sooner.

**Comment by eddyystop** [comment]
I think this issue is resolved. Feel free to reopen it if necessary.
