### ISSUE TITLE
Async functions in alterItems don't work

### ISSUE THREAD

**Issue by sean-nicholas** [feathers-plus/feathers-hooks-common#367]
### Steps to reproduce
I ran the examples from https://feathers-plus.github.io/v1/feathers-hooks-common/#alteritems

You can find my code and output here:
https://gist.github.com/sean-nicholas/c0d73e386743a2b20f690aa473d88134

### Expected behavior
alterItems should work with async functions as described in the documentation and in https://github.com/feathers-plus/feathers-hooks-common/issues/307

### Actual behavior
Promises are not resolved as you can see in the gist output file.

### System configuration

**Module versions** (especially the part that's not working): 4.8.0

**NodeJS version**: 8.1.4

**Operating System**: macOS

**Comment by sean-nicholas** [comment]
I think the example below from the documentation is rather difficult to implement because every property of the (returned) object has to be checked (deep?) if it is a promise. 

```js

alterItems(rec => {  rec.userRecord = (async () => await service.get(...) )()})
```

It might be more straight forward if the users must wrap their whole altering function in a promise / make it a async function.

What do you think?

**Comment by eddyystop** [comment]
@beeplin ^^^ any comments?

**Comment by sean-nicholas** [comment]
Okay, I will create a PR in the next few days

**Comment by eddyystop** [comment]
Could you also please submit a PR for the docs? The file is feathers-plus/docs/source/feathers-hooks-common/index.md#alteritems . Thanks.
