### ISSUE TITLE
Doc running hooks async from hook chain

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#370]
Mention https://medium.com/@mattchewone/feathersjs-background-hooks-e105bc82d84a

**Comment by NickBolles** [comment]
Isn't this just [run parallel?](https://feathers-plus.github.io/v1/feathers-hooks-common/#runparallel)

**Comment by eddyystop** [comment]
Yes, I added runParallel with Matt's approval.
