### ISSUE TITLE
createdBY, updatedBy hook

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#379]
function(context) {
  context.data.created_by = context.params.user._id;
}

**Comment by berviantoleo** [comment]
Hi,
I think this hook sound great.
Is there anyone implement it?

Thanks!

**Comment by eddyystop** [comment]
Look at the setNow hook.

**Comment by berviantoleo** [comment]
@eddyystop `setNow` hook? I think that is different, that only about time, not user
