### ISSUE TITLE
softDelete with a date instead of boolean

### ISSUE THREAD

**Issue by bertho-zero** [feathers-plus/feathers-hooks-common#385]
Currently my softDelete are done with a value deletedAt which is the date of the deletion, is it possible to modify softDelete to reproduce this behavior when it is wanted?

For the moment softDelete only allows to add a true value to the selected column.

**Comment by bertho-zero** [comment]
And for some mysql tables I have `1`/`0` instead of `true`/`false`.

**Comment by bertho-zero** [comment]
https://github.com/feathers-plus/feathers-hooks-common/issues/130

**Comment by eddyystop** [comment]
We need a new option for softDelete: boolean, 0/1, date. I'll add this next time I address the repo.

**Comment by eddyystop** [comment]
`softDelete2` is a notable improvement over `softDelete`. It only supports a `deletedAt` date of `Date.now()`.

softDelete will be released by the end of this week once its docs are done.

**Comment by eddyystop** [comment]
Published as v4.15.0
