### ISSUE TITLE
Coerce result

### ISSUE THREAD

**Issue by bertho-zero** [feathers-plus/feathers-hooks-common#387]
Hi, as mentioned [here](https://feathers-plus.github.io/v1/feathers-hooks-common/#coerce) I would like to use a validator to coerce my values, so validate should not use checkNew (like `validateSchema`).

`validate` should be able to be used on all methods and can be an after hook.

In my case I would have turned a tinyint knex into a boolean in an afterHook.

**Comment by eddyystop** [comment]
validateSchema uses Ajv which has a coersion option.

**Comment by bertho-zero** [comment]
I have created a `coerce` hook which is substantially like validate without the checkContext restriction.
