### ISSUE TITLE
Only serialize a populated field if it exists

### ISSUE THREAD

**Issue by dottodot** [feathers-plus/feathers-hooks-common#391]
I have a field in my schema that is populated by fastjoin but may or may-not exist, so ideally if it doesn't exist I just want to return a null value. However I want to use serialize compute on one of the populated fields if it doesn't exist.

I can't see a way of doing this currently, is there anything you can suggest to get around it

At the moment in the example below it will return an object with a null price value but I don't want to return an object at all I just want to ignore the computed field if finish is empty.

```
  names: {
    // Populated array
    finish: {
      // Populate field that doesn't always exist
      computed: {
        price: (finish, hook) => {
          return finish ? finish.price / 100 : null;
        }
      }
    }
  }
```

**Comment by eddyystop** [comment]
fastJoin is based on GraphQL. In GraphQL every defined field must have a value or be null.

You'll need a hook to look for and remove null fields.
