### ISSUE TITLE
Issue with populate subdocument field

### ISSUE THREAD

**Issue by nonowd** [feathers-plus/feathers-hooks-common#392]
Hi,

I have a model like this one : 

```
const orders = new Schema({
    order_number: { type: String, required: true, unique: true },
    producer: {type: Schema.Types.ObjectId, ref:"users", required: true},
    customer: {type: String},
    products: [{
      product_base: { type: Schema.Types.ObjectId, ref: "products"},
    	product_custom_id : { type: Schema.Types.ObjectId, ref: "products-custom", required: true },
      // If while product_custom is delete, the order still exists, so we want to save the minimum of product informations
      sale_presentation: { type: Schema.Types.ObjectId, ref: "products-custom.sale_presentation", required: true},
      name: String,
      variety: { type: Schema.Types.ObjectId, ref: "products-variety"},
      order_confirmation: {type: String, min: 0, max: 1, default: 0},
    	quantity: {
        number: {type: Number, default: 0},
        unity: String
      },
    	price: Number
    }],
    price: Number,
```
And I want to populate the "variety" field as it is done in the feathers-chat example we can find in the documentation. I have no problem to do that with field like the "producer" one, but I have trouble witht the "variety" and I guess because it is in a subdocument, or perhaps because I do something wrong in my after hook.

Here it is : 

```
// In this hook we will populate the variety informations
module.exports = function (options = {}) {
  return async context => {
  	// Get `app`, `method`, `params` and `result` from the hook context
    const { app, method, result, params } = context;

    // Make sure that we always have a list of products either by wrapping
    // a single product into an array or by getting the `data` from the `find` method's result
    const orders = method === 'find' ? result.data : [ result ];
    
    // Asynchronously get variety object and add it orders
    await Promise.all(orders.map(async order => {
      await order.products.map(async product => {
        const variety = await app.service('products-variety').get(product.variety, params);  
        product.variety = variety;
        //console.log(product.variety)
      })
      //console.log(order)
      return order
    }));

    // Best practice: hooks should always return the context
    return context;
  }};

```

Please let me know if yo have an idea about my issue.

Thanks,

**Comment by eddyystop** [comment]
First populate works with plain old JS objects. It has no facilities for anything else.

Second, dugs in populate will be fixed but it will not be enhanced. fastJoin should be used instead.

**Comment by nonowd** [comment]
Hi,

Thanks @eddyystop , but I am not really using the populate method here, I am populating my result the same way it is done in the chat example in feathers doc.

What I don't understand is that in my example, the "variety" field should be "populate" with the informations I get here:

> const variety = await app.service('products-variety').get(product.variety, params);

However the result doesnt show all the informations I should have.

The result give : 

> 
> {
>       ...
>       "products": [{
>          ...
>          "variety": "IDvariety"
>         }]
> }

And I should have:

> 
> {
>       ...
>       "products": [{
>          ...
>          "variety": {
                     "_id": "IDvariety"
                    "name": "NameVariety"
               }
>         }]
> }

It seems that when I affect 

> product.variety = variety;

It doesn't take it into account in my final result..

**Comment by eddyystop** [comment]
`populate` cannot populate objects which are elements of an array. Such limitations is one of the reasons why the replacement hook `fastJoin` was written.

I suggest you use `fastJoin`. Its more flexible and, with BatchLoaders, can be much faster.

**Comment by nonowd** [comment]
Ok, thanks for helping, I close this issue.

**Comment by RubyRubenstahl** [comment]
@nonowd, you may want to have a look at #386 that I filed recently. It has some code that will eventually make it into feathers-hooks-common which simplifies foreign key joins using fastjoin. It checks whether the foreign key is a single I'd or an array and performs the join accordingly.
