### ISSUE TITLE
[Question] Modify Another Resources using An Services

### ISSUE THREAD

**Issue by berviantoleo** [feathers-plus/feathers-hooks-common#407]
I want to ask about modify another resources using an services that have relation to the service. As example if I GET to /user bring me data like this,

```javascript
{
"id": "...",
"name": "...",
...
// Users data,
"messages": [
{"id": "10",
"text": "Hello!"},
...
// list of user's message
]
}
```

But, I want to create/update message resource and user data from /user, as example for update I send /PUT to /user, that modify message with ID 10 to change text.
```javascript
{
// user data, 
"messages": [
{"id": "10", "text": "Hello"},...
]
}
```

May I use this approach using hook (maybe that already have implement it)? or I must create my custom hook?

My approach is creating hooks in after, all, for user then I get the data messages send it to message service. Maybe there is another approach will be effective.

Thank you.

**Comment by eddyystop** [comment]
If you are asking if  you can make a service call to another (or the same) service in a hook, the answer is yes. In fact its not uncommon.

You have to pay attention to what `params` you pass to the called service, including authentication. https://auk.docs.feathersjs.com/guides/step-by-step/basic-feathers/writing-hooks.html#calling-a-service

**Comment by berviantoleo** [comment]
Thanks. I will try to create my own hooks.

I find another solution (same as my question) like this videos https://youtu.be/yO__Aev3TeE. In there using association with sequelize then declare the hooks to include.

But when I try, the result not same as I expected and not same with the videos. When I try (to my cases) to /POST user with messages data, my services only create to user, the message data not created. I already declare the relationship and hooks to include the model.

**Comment by eddyystop** [comment]
You will have to ask in the Slack channel https://feathersjs.slack.com/messages/C52QSFK0A/ for help with Sequelize
