### ISSUE TITLE
How to stop requests from 'external'?

### ISSUE THREAD

**Issue by flight9** [feathers-plus/feathers-hooks-common#415]
### Expected behavior
I have a service which should only be invoked inside my server, so I want to stop requests from 'external' .

### More
I found there is a predefined 'isProvider()' function inside feathers-hooks-common, but some examples only use it with iff() to control hooks, then how can it be used to stop requests to create/get/find etc?

**Comment by rondaniel00** [comment]
Hello @flight9 
Simply add the following hook:
`disallow('external')`

For example:
`
    update:     
    [ disallow('external') ],
`

**Comment by eddyystop** [comment]
Even `all: disallow('external')`.

**Comment by flight9** [comment]
Thank you @rondaniel00 @eddyystop
