### ISSUE TITLE
Create TypeScript typings for this package

### ISSUE THREAD

**Issue by davidfarinha** [feathers-plus/feathers-hooks-common#432]
### Expected behavior
TypeScript typings available through "@types/feathers-hooks-common" on npm, or type definitions bundled with this package (eg index.d.ts).

### Actual behavior
No TypeScript typings available.

I don't mind helping out with this if necessary.

Cheers

**Comment by eddyystop** [comment]
TS typings are contributions made by members of the Feathers community. The Feathers core team cannot undertaker this task as no member uses TS.

I would urge you to contribute to Feathers by providing TS typings for this repo. Thanks.

**Comment by eddyystop** [comment]
TS typings have been added to the repo. They will be included when v4.16.4 is published.
