### ISSUE TITLE
Which hook to use?

### ISSUE THREAD

**Issue by musicformellons** [feathers-plus/feathers-hooks-common#436]
After a discard and a keepInArray hook I get this result:
```
{
  "total": 1,
  "limit": 100,
  "skip": 0,
  "data": [
    {
      "point_id": 1,
      "city": "test",
      "PointPhotos": [
        {
          "photo": {
            "photo_id": 4,
            "user_id": 1,
            "url": "test",
            "created_at": "2018-09-03T11:14:09.355Z",
            "updated_at": "2018-09-03T11:14:09.355Z"
          }
        },
        {
          "photo": {
            "photo_id": 2,
            "user_id": 2,
            "url": "test",
            "created_at": "2018-09-03T11:14:09.275Z",
            "updated_at": "2018-09-03T11:14:09.275Z"
          }
        }
      ]
    }
  ]
}
```
How can I get rid of the photo keys, so I end up with this?:
```
{
  "total": 1,
  "limit": 100,
  "skip": 0,
  "data": [
    {
      "point_id": 1,
      "city": "test",
      "PointPhotos": [
        {
		"photo_id": 4,
		"user_id": 1,
		"url": "test",
		"created_at": "2018-09-03T11:14:09.355Z",
		"updated_at": "2018-09-03T11:14:09.355Z"
        },
        {
		"photo_id": 2,
		"user_id": 2,
		"url": "test",
		"created_at": "2018-09-03T11:14:09.275Z",
		"updated_at": "2018-09-03T11:14:09.275Z"
        }
      ]
    }
  ]
}
```

**Comment by eddyystop** [comment]
That is a rather unusual special need. You'll have to write your own hook for it, which would be straightforward.

**Comment by musicformellons** [comment]
[This is more of a background](https://stackoverflow.com/questions/52150349/can-you-hide-output-from-a-not-automatically-generated-join-table-using-sequel), so maybe not uncommon as I think may people shy away from using belongsToMany join tables using sequelize.

**Comment by eddyystop** [comment]
The `alterItems` hook may be of use to you. You can reform records as you want with it. https://feathers-plus.github.io/v1/feathers-hooks-common/#alteritems

**Comment by musicformellons** [comment]
Thanks. You were right, though. This can and [should be solved in Sequelize (which I use).](https://stackoverflow.com/questions/52150349/can-you-hide-output-from-a-not-automatically-generated-join-table-using-sequel)
