### ISSUE TITLE
fastJoin applied but not sent to client when called from server

### ISSUE THREAD

**Issue by Creiger** [feathers-plus/feathers-hooks-common#446]
Hi. I am not suer if it is a bug or not, but i have the folowing problem.
I have a service Users which uses fastJoin in after hooks. It works perfectly when i call the service from socketio client. But when the call comes from the server it does not send fastjoined data to client. I am checking context.result in very last after hook and at that place it is still ok, but when socket client receives updated event data, fastjoined data is missing.

**Comment by eddyystop** [comment]
I would think this something to do with when context.dispatch https://docs.feathersjs.com/api/hooks.html#contextdispatch is set. You may have to set that yourself if you want the client to get a populated record from a server-side method call.

**Comment by Creiger** [comment]
Thanks! I knew it must be my mistake. So now i just delete context.dispatch in all methods after hook if i call them from server.
