### ISSUE TITLE
How to pass query parameters from the client to fastJoin

### ISSUE THREAD

**Issue by nidkil** [feathers-plus/feathers-hooks-common#447]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
I want to pass query parameters from the client to fastJoin to enable and disable joins and control which fields are returned in the joins.

I am passing the parameters throught the url, example:

http://localhost:3030/products?categories=false&image=true

The documentation only states the following:

> // Options for hook API
> ...
> fastJoin(postResolvers, context => query) // supports queries from client
> 

But does not specify how to move the parameters from context.params.query.

Here is the code I am using in my hook.

```
const query = {
  categories: true,
  image: [['path', 'originalName']]
};

const productResolvers = {
  joins: {
    categories: ($select, ...args) => async (product, context) => { 
      initIncludeProperties(product);
      const result = await context.app.service('categories')
        .find({ 
          query: { _id: { $in: [ product.categoryIds ] }, deleted: false, active: true, 
            $select: $select || ['name', 'description'] },
          paginate: false,
          _populate: true, // stop referenced documents from including their referenced documents (no deep nesting)
          acceptLanguage: context.params.acceptLanguage
        });
      addInclude(product, 'categories', result);
    },
    image: $select => async (product, context) => resolveImage(product, context, 'image', $select)
  }
};
````

This is the actual call of the fastJoin in the hook.

```
after: {
    all: [
      fastJoin(productResolvers, context => query)
    ],
    ...
}
```

### Actual behavior

When I pass the parameters as is no results are returned. When I remove them the results include joins are returned.

Can someone please explain how to get this to work?

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by eddyystop** [comment]
If you were using Feathers/client instead of a REST URL, you would use `paramsForServer` on the client and `paramsFromClient` on the server. `paramsForServer` copies the specified props from `context.params` to `context.query.$client`. `paramsFromClient` does the opposite. 

(1) I suggest you make your REST URL compatible with the above so your server could handle calls both from Feathers' clients and REST URLs. The URL format would be something like `?$client[foo]=bar.

(2) Alternatively you could write a custom hook which moved props from `context.params.query` to `context.params`.

Once that is done, you have your "options" in `context.params` and your `context.params.query` is "clean" for the feathers call.

===========

Something like `fastJoin(productResolvers, context => query)` suggests you want your client to specify what the query should be. You'd be using something like context => `context.params.foo` and `foo` would have to be an object.  Since REST URL parameters are always passed as strings, you'd have to first convert the parameter to an object.

**Comment by nidkil** [comment]
Hi, thanks for the respons. I have got it working following your tips. The strange thing is it only works on the first call. The fastJoin includes are there on the first call. On subsequent calls, with the same or different parameters, the includes are missing. When I restart Feathers it works again on the first call.

Here is the code I put together.

```
const { setByDot } = require('feathers-hooks-common');

const defaultOptions = {
  clearQuery: false,
  createPlaceholder: true
}

module.exports = function (moveTo, moveList, options = {}) {
  return context => {
    const params = context.params;
    options = Object.assign(defaultOptions, options);

    function isBoolean(value) {
      return value === 'true' || value === 'false';
    }

    function convToBoolean(value) {
      if (isBoolean(value)) {
        value = value === 'true' ? true : false;
      }
      return value;
    }

    function isNumber(value) {
      return !isNaN(value);
    }

    function convToNumber(value) {
      if (isNumber(value)) {
        value = Number(value);
      }
      return value;
    }

    function isArray(value) {
      // To force an array enclose the value in straight brackets, example: [value],
      // this ensures that even a single value is converted to an array
      return value.indexOf(',') !== -1 || value.charAt(0) === '[';
    }

    function convToArray(value) {
      if (isArray(value)) {
        // To enforce a multi dimensional (nested) array add double brackets, example
        // [[value]]
        const multiDimensional = value.indexOf('[[') !== -1
        let values = value.replace(/(\[\[|\[|\]\]|\])/g, '').split(',');
        values.forEach(value => {
          value = convValue(value);
        });
        return multiDimensional ? [values] : values;
      }
      return value;
    }

    function convValue(value) {
      if (isBoolean(value)) {
        value = convToBoolean(value);
      } else if (isNumber(value)) {
        value = convToNumber(value);
      } else if (isArray(value)) {
        value = convToArray(value);
      }
      return value;
    }

    // If required, create empty placeholder
    if (options.createPlaceholder) setByDot(context, `params.${moveTo}`, {});

    if (params && params.query) {
      const query = params.query;

      moveList.forEach(key => {
        if (key in query) {
          // Fix the data types
          query[key] = convValue(query[key]);
          setByDot(context, `params.${moveTo}.${key}`, query[key]);
          delete query[key];
        }
      });

      // If required, remove all remaining properties from params.query to ensure the client cannot
      // pass unsupported or dangerous parameters 
      if (options.clearQuery) {
        Object.keys(query).forEach(key => {
          // Make sure we do not remove entries that start with a dolar sign ($), like the ones added 
          // by CASL
          if (key.charAt(0) !== '$') delete query[key];
        });
      }
    }

    return context;
  };
};
```

Here is the call in the hooks.

```
let query = {
  categories: [['name']],
  image: [['path', 'originalName']]
};

  before: {
    all: [
      moveParams('fastJoin.query', ['image', 'categories'], { clearQuery: true })
    ],
    ...
  }
  after: {
    all: [
      fastJoin(productResolvers, context => {
        if (context.params.fastJoin && context.params.fastJoin.query) {
          query = context.params.fastJoin.query
        }
        return query;
      }),
      ...
    ],
    ...
  },
```
Here is my url call:

```
http://localhost:3030/products?categories=true&image=[path,originalName,size]
```

When I debug the fastJoin code it in all cases calls the anonymous function I'm passing in. The difference is on the first call the data is set on context.params.fastJoin.query on the subsequent calls it is an empty object. The strange thing is that I have added a debugging hook (code below), that sends the value of the object to the console and both before and after the fastJoin hook the value is set...

```
const { getByDot } = require('feathers-hooks-common');
const logger = require('../logger');
const { neatJSON } = require('../libs/neat-json');

module.exports = function (objectName, obj) {
  return context => {
    if (obj) {
      if (typeof obj === 'string') {
        obj = getByDot(context, `params.${obj}`);
      }

      const message = ` ---------- ${context.path}.hooks::${context.type}::${context.method} ---- object: ${objectName} ----------`;
    
      logger.info(
        message + '\n' + neatJSON(obj, { wrap: 40, short: true, aligned: true, padding: 1, afterComma: 1, aroundColonN: 1 })
      );
    }

    return context;
  };
};
```
And the hooks.
```
  after: {
    all: [
      debugObject('query', query),
      debugObject('fastJoin.query', 'fastJoin.query'),
      fastJoin(productResolvers, context => {
        if (context.params.fastJoin && context.params.fastJoin.query) {
          return context.params.fastJoin.query
        }
        return query;
      }),
      debugObject('fastJoin.query', 'fastJoin.query')
    ]
    ...
  }

```
Any suggestions why the values seem to be unavailable to fastJoin in all but the first call? While they are printed out in the console before and after the call to fastJoin?

**Comment by nidkil** [comment]
I've just debugged the debug-object hook te findout why it is showing the value while fastJoin is not seeing it. The strange thing is that on the first call the second parameter, which is a string, is a string. On the subsequent calls it is an object with the expected values. When I check the context in the hook the values are missing from params.fastJoin.query. How is this possible? Where is the object comming from as the hook has the path (fastJoin.query) defined?

**Comment by eddyystop** [comment]
I don't have the time to debug your code. The first thing I would check is if you are converting your string to an object and saving the object in the same place where the string was stored. The second thing I would do is make the second call use a different value than the first, to confirm you are using the current value rather than an old one.

**Comment by nidkil** [comment]
Hi Eddy, No worries. Thx for your help. 

BTW: I have got it working with the find, but the get is still doing wiping the value somewhere. Very frustrating. What I am seeing is that the get calls the products service twice, while the find only calls it once. Is this normal?

**Comment by eddyystop** [comment]
The only service calls fastJoin makes are the ones defined in its resolver functions. However each one of these calls may cause hooks to run, and any of those hooks could call a service internally.

Furthermore the authenticate hooks makes a get call on the users service for external requests. If your issue shows itself on users, I would look at that first.
