### ISSUE TITLE
fastJoin loop

### ISSUE THREAD

**Issue by sxwebdev** [feathers-plus/feathers-hooks-common#453]
I have two services. Both of them depend on each other.

`order service`
```js
const joinFirm = {
	joins: {
		firm: () => async (order,context) =>  {
			order.firm = order.firm ? await context.app.service('firms').get(order.firm) : {};
		}
	}
}
```

and `after hook`
```js
after: {
	all: [
		fastJoin(joinFirm)
	],
	find: [],
	get: [],
	create: [],
	update: [],
	patch: [],
	remove: []
}
```
`firm service`

```js
const joinOrder = {
	joins: {
		orders: () => async (firm,context) =>  {
			firm.orders = (await context.app.service('orders').find({query:{firm:firm._id,$sort:{createdAt:-1}},pagintae:false})).data;
		}
	}
}
```

and `after hook`
```js
after: {
	all: [
		fastJoin(joinOrder)
	],
	find: [],
	get: [],
	create: [],
	update: [],
	patch: [],
	remove: []
}
```

If make a request to a order service, then the application goes into a cycle. How to fix this?
How to use the fastJoin that would not have a loop?

**Comment by eddyystop** [comment]
Including `_populate: true` in a service call will disable both fastJoin and populate from running, e.g. `get(order.firm, { _populate: true })`. See https://github.com/feathers-plus/feathers-hooks-common/blob/master/lib/services/fast-join.js#L6

**Comment by sxwebdev** [comment]
> Including `_populate: true` in a service call will disable both fastJoin and populate from running, e.g. `get(order.firm, { _populate: true })`. See https://github.com/feathers-plus/feathers-hooks-common/blob/master/lib/services/fast-join.js#L6
> 
> Feel free to continue commenting if this does not address your needs.

Thanks for the fast feedback.
Could you tell me how to deal with the case when I want to disable a specific fastJoin hook?
For example.
I call orders service, where exist this join

```js
firm: () => async (order,context) =>  {
	order.firm = order.firm ? await context.app.service('firms').get(order.firm) : {};
}
```

`Firms  service` have next joins:

```js
const joinAll = {
	joins: {
		countOrders: () => async (firm,context) =>  {
			firm.countOrders = (await context.app.service('orders').find({query:{firm:firm._id,$limit:1}})).total;
		},
		contact: () => async (firm,context) =>  {
			firm.contact = (firm.contact && firm.contact.length) ?
							await context.app.service('firm-contacts').find({query:{_id:{$in: firm.contact},$sort:{createdAt:-1}},pagintae:false})
							: []
		}
	}
}
const joinOrders = {
	joins: {
		orders: () => async (firm,context) =>  {
			firm.orders = (await context.app.service('orders').find({query:{firm:firm._id,$sort:{createdAt:-1}},pagintae:false,_populate:true})).data;
		}
	}
}
```

and after hook of `firms service`

```js
after: {
	all: [
		fastJoin(joinAll),
		alterItems( f => {if(f.inn) f.oldInn = f.inn})
	],
	find: [],
	get: [
		fastJoin(joinOrders),
	],
	create: [
		fastJoin(joinOrders),
	],
	update: [],
	patch: [
		fastJoin(joinOrders),
	],
	remove: [fastJoin(joinOrders)]
}
```

If i call from orders service like this

```js
order.firm = order.firm ? await context.app.service('firms').get(order.firm,{_populate:true}) : {};
```

`fastJoin(joinAll)` will be disabled. But I want to disable only this hook `fastJoin(joinOrders)`

**Comment by eddyystop** [comment]
There are 2 designs.

(1) For each service have a fastJoin which joins all the services recursively. Read https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#Recursive-Operations . Also read on how to prevent repeating the same code in multiple places https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#Keeping-Resolvers-DRY

Then you can simply disable all the other hooks as the presently run hook does all the joining.

(2) Condition the fastJoin for service 'users' with `iff(context => (context.params.fastJoins || []).includes('users'), fastJoin(...))`. Right before that hook, create a custom hook like
```js
context => {
   context.params.fastJoins = ['roles', 'dept', 'div'];
  return context;
}
```
which lists the fastJoins which should run.

Conclusion: I would prefer using (1) to (2) as everything for one service is nicely together rather than scattered around.
