### ISSUE TITLE
dtslint-build folder in installed package?

### ISSUE THREAD

**Issue by K3TH3R** [feathers-plus/feathers-hooks-common#461]
This is a bit strange, but I was trying to install `feathers-hooks-common` into a project using `pnpm` and `rush.io` and it would constantly choke on the installation of this library with `EEXIST: file already exists` error and the following (truncated) output:
```
/common/temp/pnpm-store/2/registry.npmjs.org/feathers-hooks-common/4.17.14/node_modules/feathers-hooks-common/dtslint-build/node_modules/typescript/lib/pt-br/diagnosticMessages.generated.json' -> 
/common/temp/node_modules/.registry.npmjs.org/feathers-hooks-common/4.17.14/node_modules/_tmp_27828_842f75df51d0959c837427c958974785/dtslint-build/node_modules/typescript/lib/pt-br/diagnosticMessages.generated.json'
```

After a little bit of investigation, it looks like there's a `dtslint-build` folder that is being inserted even though it doesn't exist within the actual Github repo. Because this `dtslint-build` folder has it's own `node_modules` directory in it, it seems like that is what `pnpm` is choking on. This is from a fresh `npm init && npm i -d feathers-hooks-common`:

<img width="199" alt="screen shot 2018-11-02 at 3 51 24 pm" src="https://user-images.githubusercontent.com/11901111/47900267-430b5e00-deb7-11e8-98e7-a606f63fd84f.png">

I assume this is happening because some sort of cleanup function from after tests/builds run in your CI/CD is being missed and the artifacts are being committed to the final build?

**Comment by eddyystop** [comment]
@j2L4e ^^^

It may take a while for a reponse as j2l4e is tied up presently.

**Comment by K3TH3R** [comment]
@eddyystop I would agree that the issue lies with pnpm because it enforces a lot more strictness upon the NPM dependency tree to alleviate [certain problems](https://rushjs.io/pages/advanced/phantom_deps/). I guess maybe the question is why a full, separate node_modules tree is being included in the NPM package?
