### ISSUE TITLE
Difference between serialize and alterItems

### ISSUE THREAD

**Issue by Sicria** [feathers-plus/feathers-hooks-common#464]
Is there a difference or preferred choice between ``serialize`` computed fields and ``alterItems``?

I've been using the computed fields method for a while now but noticed that the ``alterItems`` method is very similar and simpler to use.

Is one preferred over the other and why?

**Comment by eddyystop** [comment]
The use case for `alterItems` is modifications to the base records. Little boilerplate is wrapped about the callback function.

`serialize`  is meant to prune and calc values for populated records, which may nest deeply. Its also compatible with `dePopulate`.

`alterItems` may be simpler if you have few joined child records, and no grandchild records, and you don't use dePopulate.
