### ISSUE TITLE
Document KeepQueryInarray

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#465]
https://github.com/feathers-plus/feathers-hooks-common/pull/454

**Comment by dekelev** [comment]
https://github.com/feathers-plus/docs/pull/52

**Comment by eddyystop** [comment]
If I remember correctly, the hook has not been added to the tags at the top of the docs.

**Comment by dekelev** [comment]
[Added missing `keep-query-in-array` in hooks-api.js file](https://github.com/feathers-plus/docs/pull/52/commits/8c8c5aa2ed089c47de053384a555b87a73298a30)

**Comment by eddyystop** [comment]
Thanks!
