### ISSUE TITLE
Validation hook for restful api

### ISSUE THREAD

**Issue by penghap** [feathers-plus/feathers-hooks-common#491]
### Steps to reproduce
use validateSchema and Ajv to validate the req.query is apposite.  always get `BadRequest: Data does not match schema`.

in [get-item.js](https://github.com/feathers-plus/feathers-hooks-common/blob/fd6d4cbd1b9993152623028a2a52c89f457392b8/lib/services/get-items.js#L4) the context.data always is `undefined` because 
[context.data is a writeable property containing the data of a create, update and patch service method call.](https://github.com/feathersjs/docs/blob/master/api/hooks.md#contextdata).
I don't know how to validate the req.query in `restful api`,  could give me some help, thanks a lot, thanks a lot.

### Expected behavior
validate req.query pass

##### GET /*****?name="name"
```js
const Ajv = require('ajv');
const {validateSchema } = require('feathers-hooks-common');
const  schema = {
  type: 'object',
  required: ['username'],
  properties: {
    username: {
      type: 'string',
      minLength: 4
    },
    email: {
      type: 'string',
      format: 'email'
    },
    password: {
      type: 'string',
      minLength: 6
    }
  }
};

// Hooks
module.exports = {
  before: {
    all: [],
    find: [validateSchema(schema, Ajv)]
} 
```

### Actual behavior
BadRequest: Data does not match schema

### System configuration

**Module versions** (especially the part that's not working): 
"feathers-hooks-common": "^4.19.6"
"ajv": "^6.6.2"
"@feathersjs/feathers": "^3.1.5",  

**NodeJS version**:  v10.5.0

**Operating System**:  macOS

**Comment by eddyystop** [comment]
A get operation reads a record. You are trying to verify the contents of the read record *before* its read. The data does not exist at that point.

Perhaps you want to verify it *after* its read? If so `module.exports = { after: {...}}`.

However I don't know if verify the existing contents of a record is even a good idea. Usually you verify data you are about to write.

**Comment by penghap** [comment]
Sorry, maybe I did not describe clearly, I want to use the hook to verify the client input, req.query or req.body. I think in the server, we should verify the client input first. 

Maybe I should use a middleware, like  [express-validation](https://www.npmjs.com/package/express-validation).

Thank you for your reply.
