### ISSUE TITLE
@feathersjs/commons dependency 

### ISSUE THREAD

**Issue by PowerMogli** [feathers-plus/feathers-hooks-common#492]
### Steps to reproduce
install feathers-hooks-common and @feathersjs/feathers in client app. 

### Expected behavior
@feathersjs/commons 4.0.0 should get installed
### Actual behavior
feathers-hooks-common has a dependency of @feathersjs/commons 1.4.0 but @feathersjs/feathers has a dependency of @feathersjs/commons 4.0.0. npm installs @feathersjs/commons 1.4.0 instead of 4.0.0. 
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 9.11.1

**Operating System**: Windows 10

**Browser Version**: Chrome WebView 71.x

**Comment by eddyystop** [comment]
You have to run feathers-hooks-common thru WebPack if you want to use it client-side.
