### ISSUE TITLE
Many-to-many fastJoin

### ISSUE THREAD

**Issue by Timonzimm** [feathers-plus/feathers-hooks-common#504]
Hi all,
I was wondering if it's feasible to populate many-to-many relationships with the `fastJoin` hook.

Here is the example:
```js
projects.belongsToMany(models.users, { through: 'users_projects', as: 'members' });
```
```js
users.belongsToMany(models.projects, { through: 'users_projects', as: 'members' });
```

Previously (which works):
```js
const populateProject = context => {
  const sequelize = context.app.get('sequelizeClient')
  const { users } = sequelize.models

  context.params.sequelize = {
    include: [
      { model: users, as: 'members', attributes: ['id', 'email', 'firstname', 'lastname', 'created_at'] }
    ],
    raw: false
  }

  return context;
}
```

What I want:
```js
joins: {
    members: () => async (project, context) => project.members = await context.app.service('users_projects').find({
      query: { 
        id: { $in: project.members },
        $select: ['id', 'email', 'firstname', 'lastname']
      },
      paginate: false
    })
  }
```

But obviously the service `users_projects` doesn't exist.

How do you typically solve this with `fastJoin` ?

Best,

**Comment by eddyystop** [comment]
You would have to have many-to-many table.

**Comment by Timonzimm** [comment]
Did you even read the text and code that I took time to write?

Your answer seems irrelevant as I already have a many-to-many table created by the associations. My question is **actually** about using `fastJoin` downstream in order to join the many-to-many table.
