### ISSUE TITLE
Many-to-many fastJoin

### ISSUE THREAD

**Issue by Timonzimm** [feathers-plus/feathers-hooks-common#505]
**Note:** Yes this is a repost because I feel like @eddyystop didn't properly read my question in #504 .

Hi all,
I was wondering if it's feasible to populate many-to-many relationships with the `fastJoin` hook.

Here is the example:
```js
projects.belongsToMany(models.users, { through: 'users_projects', as: 'members' });
```
```js
users.belongsToMany(models.projects, { through: 'users_projects', as: 'members' });
```

Previously (which works):
```js
const populateProject = context => {
  const sequelize = context.app.get('sequelizeClient')
  const { users } = sequelize.models

  context.params.sequelize = {
    include: [
      { model: users, as: 'members', attributes: ['id', 'email', 'firstname', 'lastname', 'created_at'] }
    ],
    raw: false
  }

  return context;
}
```

What I want:
```js
joins: {
    members: () => async (project, context) => project.members = await context.app.service('users_projects').find({
      query: { 
        id: { $in: project.members },
        $select: ['id', 'email', 'firstname', 'lastname']
      },
      paginate: false
    })
  }
```

But obviously the service `users_projects` doesn't exist.

How do you typically solve this with `fastJoin` ?

Best,

**Comment by 1valdis** [comment]
For this type of thing, I usually just create a service for the joining table, and use it to make two joins (firstly join the joining table, then join items themselves). This is the simplest (and pretty dumb) solution we came to and it's working pretty well without any need to change.

**Comment by eddyystop** [comment]
That is what I would do for a db that did not support many to many. Maybe optimize it a bit by filtering which records are considered.
