### ISSUE TITLE
query regarding set response to hook :after create

### ISSUE THREAD

**Issue by sanmeetsingh** [feathers-plus/feathers-hooks-common#507]
I am unable to set response after create 
hook.result.thumbnail = res._id

the process is like following:-
1) i am using fs model to upload video
2) after upload i am creating thumbnail by using "ThumbnailGenerator" model in hook :after create 
3)in this i make another entry in mongodb for thumbnail , after insertion i take the id of that and patch in mongodb of video file
4) and then set the 
hook.result.thumbanil = res._id 

but this is not working

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by eddyystop** [comment]
Sorry but I fail to see that this us related to any of the common hooks. Please post your question in feathersjs.

**Comment by sanmeetsingh** [comment]
should i raise new issue ,or any method to edit issue
